apiVersion : networking.k8s.io/v1
kind : Ingress
metadata :
  name : ingress-service
  annotations :
    kubernetes.io/ingress.class : nginx
    nginx.ingress.kubernetes.io/use-regex : "true"
    nginx.ingress.kubernetes.io/proxy-body-size : "5000m"
spec :
  rules :
    - host : jogging.dev
      http :
        paths :
          - path : /api/?(.*)
            pathType : Prefix
            backend :
              service :
                name : jogging-srv
                port :
                  number : 3000